/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangLayoutRouteImport } from './routes/$lang/_layout'
import { Route as LangLayoutIndexRouteImport } from './routes/$lang/_layout/index'
import { Route as LangLayoutRepairsIndexRouteImport } from './routes/$lang/_layout/repairs/index'
import { Route as LangLayoutRepairsCreateIndexRouteImport } from './routes/$lang/_layout/repairs/create/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangLayoutRoute = LangLayoutRouteImport.update({
  id: '/$lang/_layout',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const LangLayoutIndexRoute = LangLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangLayoutRoute,
} as any)
const LangLayoutRepairsIndexRoute = LangLayoutRepairsIndexRouteImport.update({
  id: '/repairs/',
  path: '/repairs/',
  getParentRoute: () => LangLayoutRoute,
} as any)
const LangLayoutRepairsCreateIndexRoute =
  LangLayoutRepairsCreateIndexRouteImport.update({
    id: '/repairs/create/',
    path: '/repairs/create/',
    getParentRoute: () => LangLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangLayoutRouteWithChildren
  '/$lang/': typeof LangLayoutIndexRoute
  '/$lang/repairs/': typeof LangLayoutRepairsIndexRoute
  '/$lang/repairs/create/': typeof LangLayoutRepairsCreateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang': typeof LangLayoutIndexRoute
  '/$lang/repairs': typeof LangLayoutRepairsIndexRoute
  '/$lang/repairs/create': typeof LangLayoutRepairsCreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang/_layout': typeof LangLayoutRouteWithChildren
  '/$lang/_layout/': typeof LangLayoutIndexRoute
  '/$lang/_layout/repairs/': typeof LangLayoutRepairsIndexRoute
  '/$lang/_layout/repairs/create/': typeof LangLayoutRepairsCreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/'
    | '/$lang/repairs/'
    | '/$lang/repairs/create/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$lang' | '/$lang/repairs' | '/$lang/repairs/create'
  id:
    | '__root__'
    | '/'
    | '/$lang/_layout'
    | '/$lang/_layout/'
    | '/$lang/_layout/repairs/'
    | '/$lang/_layout/repairs/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangLayoutRoute: typeof LangLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/_layout': {
      id: '/$lang/_layout'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/_layout/': {
      id: '/$lang/_layout/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangLayoutIndexRouteImport
      parentRoute: typeof LangLayoutRoute
    }
    '/$lang/_layout/repairs/': {
      id: '/$lang/_layout/repairs/'
      path: '/repairs'
      fullPath: '/$lang/repairs/'
      preLoaderRoute: typeof LangLayoutRepairsIndexRouteImport
      parentRoute: typeof LangLayoutRoute
    }
    '/$lang/_layout/repairs/create/': {
      id: '/$lang/_layout/repairs/create/'
      path: '/repairs/create'
      fullPath: '/$lang/repairs/create/'
      preLoaderRoute: typeof LangLayoutRepairsCreateIndexRouteImport
      parentRoute: typeof LangLayoutRoute
    }
  }
}

interface LangLayoutRouteChildren {
  LangLayoutIndexRoute: typeof LangLayoutIndexRoute
  LangLayoutRepairsIndexRoute: typeof LangLayoutRepairsIndexRoute
  LangLayoutRepairsCreateIndexRoute: typeof LangLayoutRepairsCreateIndexRoute
}

const LangLayoutRouteChildren: LangLayoutRouteChildren = {
  LangLayoutIndexRoute: LangLayoutIndexRoute,
  LangLayoutRepairsIndexRoute: LangLayoutRepairsIndexRoute,
  LangLayoutRepairsCreateIndexRoute: LangLayoutRepairsCreateIndexRoute,
}

const LangLayoutRouteWithChildren = LangLayoutRoute._addFileChildren(
  LangLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangLayoutRoute: LangLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
